#!/bin/bash
 
#-------------------------------------------------------
echo Loading public4over6 module...
insmod public4over6.ko
ifconfig public4over6 up
ip addr add 58.205.200.1/24 broadcast 58.205.200.255 dev public4over6
sysctl net.ipv4.ip_forward=1
iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1420
#-------------------------------------------------------

 




